version: '3'
services:
 ghost:
  depends_on:
   - db
  image: ghost:1-alpine
  restart: always
  ports:
   - 2368:2368
  environment:
   database__client: mysql
   database__connection__database: ghost
   database__connection__host: db:3306
   database__connection__user: ghost
   database__connection__password: ghost

 db:
  image: mysql:5.7
  environment:
   MYSQL_ROOT_PASSWORD: ghost
   MYSQL_DATABASE: ghost
   MYSQL_USER: ghost
   MYSQL_PASSWORD: ghost
